In [41]:
import pandas as pd

In [42]:
df_records = pd.read_csv("../data/raw/records.csv")
df_pseudo = pd.read_excel("../data/external/pseudo_bookings.xlsx")

In [43]:
df_records.head()

,id,username,booking,created_at
0,1,test,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-05 16:05:19.533091+00:00
1,19,0,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-08 15:14:18.789640+00:00
2,20,00860768,"Date: 2025-08-31 , Time: 10:20 - 12:00",2025-08-10 07:39:16.993798+00:00
3,21,00860768,"Date: 2025-08-12 , Time: 14:15 - 15:05",2025-08-10 17:09:18.087665+00:00
4,22,00860768,"Date: 2025-08-19 , Time: 11:15 - 12:05",2025-08-10 17:09:40.512199+00:00

In [51]:
df_pseudo.head()

    name lesson_date lesson_time booking date booking time  type_of_booking
0  anmol  2025-12-04    16:25:00   2025-12-04     14:31:00                1
1  anmol  2025-12-04    16:25:00   2025-12-04     14:49:00                1
2  anmol  2025-12-04    16:25:00   2025-12-04     14:51:00                1
3  anmol  2025-12-04    16:25:00   2025-12-04     14:53:00                1
4  anmol  2025-12-04    16:25:00   2025-12-04     14:56:00                1

In [52]:
df_records.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 433 entries, 0 to 432
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          433 non-null    int64
 1   username    433 non-null    str
 2   booking     428 non-null    str
 3   created_at  433 non-null    str
dtypes: int64(1), str(3)
memory usage: 107.7 KB

In [53]:
df_pseudo.info(memory_usage="deep")

<class 'pandas.DataFrame'>
RangeIndex: 308 entries, 0 to 307
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             308 non-null    str
 1   lesson_date      90 non-null     datetime64[us]
 2   lesson_time      90 non-null     object
 3   booking date     308 non-null    datetime64[us]
 4   booking time     308 non-null    object
 5   type_of_booking  308 non-null    int64
dtypes: datetime64[us](2), int64(1), object(2), str(1)
memory usage: 51.5 KB