In [1]:
import pandas as pd
from pandas import Series
import re
from cdc_ml.config import RAW_DATA_DIR
from cdc_ml.datasets.records.records import clean_df

2026-05-06 14:15:47.300 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df = pd.read_csv(RAW_DATA_DIR/"records.csv")

In [3]:
df.head()

,id,username,booking,created_at
0,1,test,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-05 16:05:19.533091+00:00
1,19,0,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-08 15:14:18.789640+00:00
2,20,00860768,"Date: 2025-08-31 , Time: 10:20 - 12:00",2025-08-10 07:39:16.993798+00:00
3,21,00860768,"Date: 2025-08-12 , Time: 14:15 - 15:05",2025-08-10 17:09:18.087665+00:00
4,22,00860768,"Date: 2025-08-19 , Time: 11:15 - 12:05",2025-08-10 17:09:40.512199+00:00

In [4]:
df = clean_df(df)

2026-05-06 14:15:47.655 | INFO     | cdc_ml.datasets.records.records:clean_df:114 - Pre-Clean: 432 rows
2026-05-06 14:15:47.669 | INFO     | cdc_ml.datasets.records.records:clean_df:123 - Main customers only: 279 row
2026-05-06 14:15:47.675 | INFO     | cdc_ml.datasets.records.records:clean_df:130 - Post-Clean: 219 rows

In [5]:
df.head()

,id,username,booking,created_at,lesson_at,booking_at
42,60,ajithak,"Date: 2025-08-28 , Time: 18:50 - 20:30",2025-08-21 01:24:06.300383+00:00,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00
43,61,ajithak,"Date: 2025-08-28 , Time: 20:40 - 22:20",2025-08-21 01:24:16.048708+00:00,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00
44,62,addity,"Date: 2025-09-21 , Time: 14:35 - 16:15",2025-08-22 16:57:26.576198+00:00,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00
45,63,bryan,"Date: 2025-08-28 , Time: 20:40 - 22:20",2025-08-25 04:06:06.539664+00:00,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00
55,73,bryan,"Date: 2025-08-31 , Time: 12:45 - 14:25",2025-08-26 04:50:24.317931+00:00,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00

In [6]:
df[df["username"]=="jy"]

,id,username,booking,created_at,lesson_at,booking_at
99,117,jy,"Date: 2025-09-23 , Time: 10:20 - 12:00",2025-09-16 22:40:23.094577+00:00,2025-09-23 10:20:00+08:00,2025-09-17 06:40:23.094577+08:00
100,118,jy,"Date: 2025-09-25 , Time: 08:30 - 10:10",2025-09-17 06:57:40.760119+00:00,2025-09-25 08:30:00+08:00,2025-09-17 14:57:40.760119+08:00
101,119,jy,"Date: 2025-09-25 , Time: 16:25 - 18:05",2025-09-18 03:18:01.130913+00:00,2025-09-25 16:25:00+08:00,2025-09-18 11:18:01.130913+08:00
102,120,jy,"Date: 2025-09-25 , Time: 18:50 - 20:30",2025-09-18 03:18:15.920648+00:00,2025-09-25 18:50:00+08:00,2025-09-18 11:18:15.920648+08:00
115,133,jy,"Date: 2025-11-17 , Time: 20:40 - 22:20",2025-10-14 23:27:39.163745+00:00,2025-11-17 20:40:00+08:00,2025-10-15 07:27:39.163745+08:00
116,134,jy,"Date: 2025-11-17 , Time: 20:40 - 22:20",2025-10-14 23:27:39.908192+00:00,2025-11-17 20:40:00+08:00,2025-10-15 07:27:39.908192+08:00
117,135,jy,"Date: 2025-11-18 , Time: 20:40 - 22:20",2025-10-14 23:27:51.700752+00:00,2025-11-18 20:40:00+08:00,2025-10-15 07:27:51.700752+08:00
140,158,jy,"Date: 2025-11-03 , Time: 20:40 - 22:20",2025-10-29 07:46:54.076162+00:00,2025-11-03 20:40:00+08:00,2025-10-29 15:46:54.076162+08:00
141,160,jy,"Date: 2025-11-04 , Time: 20:40 - 22:20",2025-10-29 10:29:57.782414+00:00,2025-11-04 20:40:00+08:00,2025-10-29 18:29:57.782414+08:00
142,159,jy,"Date: 2025-11-04 , Time: 20:40 - 22:20",2025-10-29 10:29:57.792843+00:00,2025-11-04 20:40:00+08:00,2025-10-29 18:29:57.792843+08:00
162,180,jy,"Date: 2025-11-09 , Time: 12:45 - 14:25",2025-11-03 06:47:23.781367+00:00,2025-11-09 12:45:00+08:00,2025-11-03 14:47:23.781367+08:00
363,381,jy,"Slots booked:\nDate: 27/01/2026, Time: 14:35 -...",2026-01-26 13:12:36.786380+00:00,2026-01-27 14:35:00+08:00,2026-01-26 21:12:36.786380+08:00
383,401,jy,"Slots booked:\nDate: 23/02/2026, Time: 18:50 -...",2026-02-13 06:24:16.808427+00:00,2026-02-23 18:50:00+08:00,2026-02-13 14:24:16.808427+08:00