In [7]:
import pandas as pd
from pandas import Series
import re
from cdc_ml.config import RAW_DATA_DIR,PROPER_RECORDS_RAW
from cdc_ml.datasets.proper_records.proper_records import clean_df

In [8]:
df = pd.read_csv(PROPER_RECORDS_RAW)

In [9]:
df.head()

,id,username,booking,created_at
0,1,test,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-05 16:05:19.533091+00:00
1,19,0,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-08 15:14:18.789640+00:00
2,20,00860768,"Date: 2025-08-31 , Time: 10:20 - 12:00",2025-08-10 07:39:16.993798+00:00
3,21,00860768,"Date: 2025-08-12 , Time: 14:15 - 15:05",2025-08-10 17:09:18.087665+00:00
4,22,00860768,"Date: 2025-08-19 , Time: 11:15 - 12:05",2025-08-10 17:09:40.512199+00:00

In [10]:
df = clean_df(df)

2026-05-08 18:10:16.435 | INFO     | cdc_ml.datasets.proper_records.proper_records:clean_df:122 - Pre-Clean: 432 rows
2026-05-08 18:10:16.450 | INFO     | cdc_ml.datasets.proper_records.proper_records:clean_df:129 - Main customers only: 279 row
2026-05-08 18:10:16.461 | INFO     | cdc_ml.datasets.proper_records.proper_records:clean_df:135 - Post-Clean: 219 rows

In [11]:
df.head()

,username,lesson_at,booking_at,booking_type
42,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0
43,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0
44,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0
45,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0
55,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 219 entries, 42 to 429
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   username      219 non-null    str
 1   lesson_at     219 non-null    datetime64[ns, Asia/Singapore]
 2   booking_at    219 non-null    datetime64[ns, Asia/Singapore]
 3   booking_type  219 non-null    int64
dtypes: datetime64[ns, Asia/Singapore](2), int64(1), str(1)
memory usage: 9.5 KB