In [1]:
import pandas as pd
from pandas import Series
import re
from cdc_ml.config import RAW_DATA_DIR
from cdc_ml.dataset.records import clean

2026-05-03 22:14:29.530 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df = pd.read_csv(RAW_DATA_DIR/"records.csv")

In [3]:
df.head()

,id,username,booking,created_at
0,1,test,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-05 16:05:19.533091+00:00
1,19,0,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-08 15:14:18.789640+00:00
2,20,00860768,"Date: 2025-08-31 , Time: 10:20 - 12:00",2025-08-10 07:39:16.993798+00:00
3,21,00860768,"Date: 2025-08-12 , Time: 14:15 - 15:05",2025-08-10 17:09:18.087665+00:00
4,22,00860768,"Date: 2025-08-19 , Time: 11:15 - 12:05",2025-08-10 17:09:40.512199+00:00

In [4]:
df = clean(df)

2026-05-03 22:14:29.679 | INFO     | cdc_ml.dataset.records:clean:85 - Pre-Clean: 437 rows
2026-05-03 22:14:29.701 | INFO     | cdc_ml.dataset.records:clean:93 - Main customers only: 283 row
2026-05-03 22:14:29.708 | INFO     | cdc_ml.dataset.records:clean:100 - Post-Clean: 227 rows

In [5]:
df.head()

,id,username,booking,created_at,lesson_timestamp,booking_timestamp
42,60,ajithak,"Date: 2025-08-28 , Time: 18:50 - 20:30",2025-08-21 01:24:06.300383+00:00,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00
43,61,ajithak,"Date: 2025-08-28 , Time: 20:40 - 22:20",2025-08-21 01:24:16.048708+00:00,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00
44,62,addity,"Date: 2025-09-21 , Time: 14:35 - 16:15",2025-08-22 16:57:26.576198+00:00,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00
45,63,bryan,"Date: 2025-08-28 , Time: 20:40 - 22:20",2025-08-25 04:06:06.539664+00:00,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00
55,73,bryan,"Date: 2025-08-31 , Time: 12:45 - 14:25",2025-08-26 04:50:24.317931+00:00,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00