In [1]:
import pandas as pd
from cdc_ml.config import EXTERNAL_DATA_DIR,PSEUDO_BOOKINGS_EXTERNAL
from cdc_ml.datasets.pseudo_records.pseudo_records import clean_df

2026-05-08 18:10:58.008 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df = pd.read_excel(PSEUDO_BOOKINGS_EXTERNAL)

In [3]:
df.head()

    name lesson_date lesson_time booking date booking time  type_of_booking
0  anmol  2025-12-04    16:25:00   2025-12-04     14:31:00                1
1  anmol  2025-12-04    16:25:00   2025-12-04     14:49:00                1
2  anmol  2025-12-04    16:25:00   2025-12-04     14:51:00                1
3  anmol  2025-12-04    16:25:00   2025-12-04     14:53:00                1
4  anmol  2025-12-04    16:25:00   2025-12-04     14:56:00                1

In [4]:
df = clean_df(df)

In [5]:
df.head()

  username  booking_type                 lesson_at                booking_at
0    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:31:00+08:00
1    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:49:00+08:00
2    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:51:00+08:00
3    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:53:00+08:00
4    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:56:00+08:00

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 305 entries, 0 to 304
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   username      305 non-null    str
 1   booking_type  305 non-null    int64
 2   lesson_at     91 non-null     datetime64[ns, Asia/Singapore]
 3   booking_at    305 non-null    datetime64[ns, Asia/Singapore]
dtypes: datetime64[ns, Asia/Singapore](2), int64(1), str(1)
memory usage: 11.0 KB