In [1]:
import pandas as pd
from cdc_ml.config import INTERIM_DATA_DIR,RAW_DATA_DIR
from cdc_ml.datasets.merge.merge import merge_records_pseudo

2026-05-07 12:42:38.696 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df_records = pd.read_parquet(INTERIM_DATA_DIR/"records.parquet")
df_pseudo = pd.read_parquet(INTERIM_DATA_DIR/"pseudo.parquet")

In [3]:
df_records.head()

,username,lesson_at,booking_at,booking_type
0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0
1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0
2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0
3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0
4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0

In [4]:
df_pseudo.head()

  username  booking_type                 lesson_at                booking_at
0    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:31:00+08:00
1    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:49:00+08:00
2    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:51:00+08:00
3    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:53:00+08:00
4    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:56:00+08:00

In [5]:
df_r_p = merge_records_pseudo(df_records,df_pseudo)

In [6]:
df_r_p

,id,username,lesson_at,booking_at,booking_type
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0
...,...,...,...,...,...
519,519,tomato,NaT,2026-01-01 00:01:00+08:00,1
520,520,bhara,2025-11-04 18:50:00+08:00,2025-10-28 13:53:00+08:00,1
521,521,d,2025-11-07 18:50:00+08:00,2025-10-28 17:10:00+08:00,1
522,522,bhara,2025-11-03 16:25:00+08:00,2025-10-29 15:56:00+08:00,1
523,523,bhara,2025-11-04 18:50:00+08:00,2025-10-29 16:34:00+08:00,1