In [3]:
import pandas as pd
from cdc_ml.config import PROPER_RECORDS_INTERIM,PSEUDO_BOOKINGS_INTERIM,CUSTOMER_CLASS_PROCESSED
from cdc_ml.datasets.merge.merge_records import merge_df

In [4]:
df_records = pd.read_parquet(PROPER_RECORDS_INTERIM)
df_pseudo = pd.read_parquet(PSEUDO_BOOKINGS_INTERIM)
df_class = pd.read_parquet(CUSTOMER_CLASS_PROCESSED)

In [5]:
df_records.head()

,username,lesson_at,booking_at,booking_type
0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0
1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0
2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0
3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0
4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0

In [6]:
df_pseudo.head()

  username  booking_type                 lesson_at                booking_at
0    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:31:00+08:00
1    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:49:00+08:00
2    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:51:00+08:00
3    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:53:00+08:00
4    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:56:00+08:00

In [7]:
df_class.head()

     username              class_type  is_one_team
0  admin user                      3a            0
1          jj                      3a            0
2           b                      3a            0
3           g                      3a            0
4    shahtiya  CLASS 3 PRACTICAL TEST            0

In [8]:
df = merge_df(df_records,df_pseudo,df_class)

In [9]:
df.head()

,id,username,lesson_at,booking_at,booking_type,class_type,is_one_team
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0,3,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0,3,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0,3a,1
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0,3a,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0,3a,0

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 524 entries, 0 to 523
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            524 non-null    int64
 1   username      524 non-null    str
 2   lesson_at     310 non-null    datetime64[ns, Asia/Singapore]
 3   booking_at    524 non-null    datetime64[ns, Asia/Singapore]
 4   booking_type  524 non-null    int64
 5   class_type    524 non-null    str
 6   is_one_team   524 non-null    int64
dtypes: datetime64[ns, Asia/Singapore](2), int64(3), str(2)
memory usage: 32.0 KB

In [11]:
df["username"].value_counts()

username
anmol      109
jy          41
mya         39
apple       37
poopie      35
jun         30
kim         27
joy         27
srpr        21
tomato      20
flower      18
faith       14
addity       9
bryan        9
anaya        9
brendon      7
aswath       7
ryan         6
ali          6
matt         5
nur          5
sara         4
carol        4
max          4
np           4
lucinda      3
fir          3
phuc         3
gohguan      3
pakning      3
bhara        3
ajithak      2
isyaf        2
natar        2
bw           1
ranjith      1
d            1
Name: count, dtype: int64