In [1]:
import pandas as pd
from cdc_ml.config import PROPER_RECORDS_INTERIM,PSEUDO_BOOKINGS_INTERIM
from cdc_ml.datasets.merge.merge_records import merge_df

2026-06-06 15:14:25.133 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df_records = pd.read_parquet(PROPER_RECORDS_INTERIM)
df_pseudo = pd.read_parquet(PSEUDO_BOOKINGS_INTERIM)

In [3]:
df_records.info()

<class 'pandas.DataFrame'>
RangeIndex: 219 entries, 0 to 218
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   username      219 non-null    str
 1   lesson_at     219 non-null    datetime64[ns, Asia/Singapore]
 2   booking_at    219 non-null    datetime64[ns, Asia/Singapore]
 3   booking_type  219 non-null    int64
dtypes: datetime64[ns, Asia/Singapore](2), int64(1), str(1)
memory usage: 7.9 KB

In [4]:
df_pseudo.info()

<class 'pandas.DataFrame'>
RangeIndex: 280 entries, 0 to 279
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   username      280 non-null    str
 1   booking_type  280 non-null    int64
 2   lesson_at     91 non-null     datetime64[ns, Asia/Singapore]
 3   booking_at    280 non-null    datetime64[ns, Asia/Singapore]
dtypes: datetime64[ns, Asia/Singapore](2), int64(1), str(1)
memory usage: 10.1 KB

In [5]:
df_records.head()

,username,lesson_at,booking_at,booking_type
0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0
1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0
2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0
3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0
4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0

In [6]:
df_pseudo.head()

  username  booking_type                 lesson_at                booking_at
0    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:31:00+08:00
1    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:49:00+08:00
2    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:51:00+08:00
3    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:53:00+08:00
4    anmol             1 2025-12-04 16:25:00+08:00 2025-12-04 14:56:00+08:00

In [7]:
df = merge_df(df_records,df_pseudo)

In [8]:
df.head()

,id,username,lesson_at,booking_at,booking_type
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 499 entries, 0 to 498
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            499 non-null    int64
 1   username      499 non-null    str
 2   lesson_at     310 non-null    datetime64[ns, Asia/Singapore]
 3   booking_at    499 non-null    datetime64[ns, Asia/Singapore]
 4   booking_type  499 non-null    int64
dtypes: datetime64[ns, Asia/Singapore](2), int64(2), str(1)
memory usage: 21.7 KB