In [1]:
import pandas as pd
from cdc_ml.config import EXTERNAL_DATA_DIR,BOOKING_CYCLES_EXTERNAL
from cdc_ml.datasets.constants import TIMEZONE
from cdc_ml.datasets.cycle.cycle import clean_df
import numpy as np

2026-06-09 02:11:56.518 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df = pd.read_excel(BOOKING_CYCLES_EXTERNAL)

In [3]:
df.head()

,username,cycle start date,cycle start time,preference,range,cycle end date,cycle end time,cycle_end_reason
0,ajithak,2025-08-19,09:15:00,"monday to saturday after 5pm , sunday anytime",till next week,2025-08-21,11:00:00,completed
1,addity,2025-08-13,21:00:00,"weeday after 7 , no tues and thurs",before oct,2025-08-28,11:36:00,completed
2,addity,2025-10-17,00:00:00,"anytime on weekends , weekday after 630pm",26 oct to 14 dec,2025-10-17,20:00:00,completed
3,addity,2026-01-16,20:00:00,"friday and weekends anytime, other weekdays af...",Jan and feb,2026-01-19,00:00:00,completed
4,bryan,2025-08-22,00:48:00,"before 25 sept , weekday after 730pm , 12 pm o...",NaN,2025-09-05,16:00:00,completed

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   username          122 non-null    str
 1   cycle start date  122 non-null    datetime64[us]
 2   cycle start time  122 non-null    object
 3   preference        91 non-null     object
 4   range             84 non-null     object
 5   cycle end date    122 non-null    datetime64[us]
 6   cycle end time    122 non-null    object
 7   cycle_end_reason  107 non-null    str
dtypes: datetime64[us](2), object(4), str(2)
memory usage: 9.2+ KB

In [5]:
df = clean_df(df)

2026-06-09 02:11:56.898 | INFO     | cdc_ml.datasets.cycle.cycle:clean_df:54 - Pre cleaning:122 rows x 8 columns

In [6]:
df.tail()

,id,username,preference,range,cycle_end_reason,cycle_start,cycle_end
117,117,ali,whole apr anytime,NaN,NaN,2026-03-25 00:00:00+08:00,2026-04-10 23:59:00+08:00
118,118,ali,whole apr anytime,NaN,NaN,2026-04-21 00:00:00+08:00,2026-04-25 23:59:00+08:00
119,119,bhara,"slot 5,6,7 all day 25 oct to 30 nov",NaN,NaN,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00
120,120,d,"27 oct to 31 dec , 6,7",NaN,NaN,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00
121,121,addity,"anytime on weekends , weekday after 630pm",26 oct to 14 dec,completed,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 122 entries, 0 to 121
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                122 non-null    int64
 1   username          122 non-null    str
 2   preference        91 non-null     str
 3   range             84 non-null     str
 4   cycle_end_reason  107 non-null    str
 5   cycle_start       122 non-null    datetime64[ns, Asia/Singapore]
 6   cycle_end         122 non-null    datetime64[ns, Asia/Singapore]
dtypes: datetime64[ns, Asia/Singapore](2), int64(1), str(4)
memory usage: 12.5 KB

In [8]:
df.describe()

               id
count  122.000000
mean    60.500000
std     35.362409
min      0.000000
25%     30.250000
50%     60.500000
75%     90.750000
max    121.000000