In [1]:
import pandas as pd
from cdc_ml.datasets.poll.poll import generate_df
from cdc_ml.config import BOOKING_CYCLES_PROCESSED,RECORDS_PROCESSED

2026-06-09 01:37:50.960 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df_cycle = pd.read_parquet(BOOKING_CYCLES_PROCESSED)
df_records = pd.read_parquet(RECORDS_PROCESSED)

In [3]:
df = generate_df(df_cycle,df_records)

2026-06-09 01:37:51.600 | INFO     | cdc_ml.datasets.poll.poll:validate_booking_records:64 - All booking records are validated against booking cycle...

In [4]:
df.head()

,id,username,cycle_start,cycle_end,polling_at,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle,has_booking
0,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 09:00:00+08:00,8,19,1,9,8,19,1,9,0.0,False
1,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 10:00:00+08:00,8,19,1,9,8,19,1,10,1.0,False
2,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 11:00:00+08:00,8,19,1,9,8,19,1,11,2.0,False
3,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 12:00:00+08:00,8,19,1,9,8,19,1,12,3.0,False
4,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 13:00:00+08:00,8,19,1,9,8,19,1,13,4.0,False

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 29612 entries, 0 to 29611
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 29612 non-null  int64
 1   username           29612 non-null  str
 2   cycle_start        29612 non-null  datetime64[us, Asia/Singapore]
 3   cycle_end          29612 non-null  datetime64[us, Asia/Singapore]
 4   polling_at         29612 non-null  datetime64[us, Asia/Singapore]
 5   cycle_start_month  29612 non-null  int32
 6   cycle_start_day    29612 non-null  int32
 7   cycle_start_dow    29612 non-null  int32
 8   cycle_start_hour   29612 non-null  int32
 9   polling_month      29612 non-null  int32
 10  polling_day        29612 non-null  int32
 11  polling_dow        29612 non-null  int32
 12  polling_hour       29612 non-null  int32
 13  hours_into_cycle   29612 non-null  float64
 14  has_booking        29612 non-null  bool
dtypes: bool(1), datetime64[us, Asia/Singapore](3), float64(1), int32(8), int64(1), str(1)
memory usage: 2.4 MB

In [6]:
df.describe()

,id,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
count,29612.000000,29612.000000,29612.000000,29612.000000,29612.000000,29612.000000,29612.000000,29612.000000,29612.000000,29612.000000
mean,61.693131,7.286911,14.742469,2.645684,7.254930,7.014183,15.459239,2.967817,11.571289,204.017560
std,36.999631,4.168200,9.179308,1.824161,8.461078,4.259546,8.669699,1.970060,6.929823,191.773874
min,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000
25%,28.000000,3.000000,8.000000,1.000000,0.000000,3.000000,8.000000,1.000000,6.000000,65.000000
50%,59.000000,9.000000,12.000000,2.000000,0.000000,9.000000,15.000000,3.000000,12.000000,153.000000
75%,95.000000,11.000000,23.000000,4.000000,16.000000,11.000000,23.000000,5.000000,18.000000,280.000000
max,121.000000,12.000000,31.000000,6.000000,23.000000,12.000000,31.000000,6.000000,23.000000,1175.000000