In [14]:
import pandas as pd
from cdc_ml.datasets.poll.poll import generate_df
from cdc_ml.config import BOOKING_CYCLES_PROCESSED,RECORDS_PROCESSED

In [15]:
df_cycle = pd.read_parquet(BOOKING_CYCLES_PROCESSED)
df_records = pd.read_parquet(RECORDS_PROCESSED)

In [16]:
df = generate_df(df_cycle,df_records)

2026-05-15 15:50:18.067 | INFO     | cdc_ml.datasets.poll.poll:validate_booking_records:53 - All booking records are validated against booking cycle...

In [17]:
df.head()

,id,username,cycle_start,cycle_end,polling_at,booking_hour,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
0,0,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-13 21:00:00+08:00,NaT,False,8,13,2,21,8,13,2,21,0.0
1,1,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-13 22:00:00+08:00,NaT,False,8,13,2,21,8,13,2,22,1.0
2,2,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-13 23:00:00+08:00,NaT,False,8,13,2,21,8,13,2,23,2.0
3,3,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-14 00:00:00+08:00,NaT,False,8,13,2,21,8,14,3,0,3.0
4,4,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-14 01:00:00+08:00,NaT,False,8,13,2,21,8,14,3,1,4.0

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32634 entries, 0 to 32633
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 32634 non-null  int64
 1   username           32634 non-null  str
 2   cycle_start        32634 non-null  datetime64[ns, Asia/Singapore]
 3   cycle_end          32634 non-null  datetime64[ns, Asia/Singapore]
 4   polling_at         32634 non-null  datetime64[ns, Asia/Singapore]
 5   booking_hour       538 non-null    datetime64[ns, Asia/Singapore]
 6   has_booking        32634 non-null  bool
 7   cycle_start_month  32634 non-null  int32
 8   cycle_start_day    32634 non-null  int32
 9   cycle_start_dow    32634 non-null  int32
 10  cycle_start_hour   32634 non-null  int32
 11  polling_month      32634 non-null  int32
 12  polling_day        32634 non-null  int32
 13  polling_dow        32634 non-null  int32
 14  polling_hour       32634 non-null  int32
 15  hours_into_cycle   32634 non-null  float64
dtypes: bool(1), datetime64[ns, Asia/Singapore](4), float64(1), int32(8), int64(1), str(1)
memory usage: 2.9 MB

In [19]:
df["username"].unique()

<ArrowStringArray>
[ 'addity', 'ajithak',     'ali',   'anaya',   'anmol',   'apple',  'aswath',
   'bhara', 'brendon',   'bryan',      'bw',   'carol',       'd',   'faith',
     'fir',  'flower', 'gohguan',   'isyaf',     'joy',     'jun',      'jy',
     'kim', 'lucinda',    'matt',     'max',     'mya',   'natar',      'np',
     'nur', 'pakning',    'phuc',  'poopie', 'ranjith',    'ryan',    'sara',
    'srpr',  'tomato']
Length: 37, dtype: str

In [20]:
df.loc[df["has_booking"]==1]

,id,username,cycle_start,cycle_end,polling_at,booking_hour,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
219,219,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-23 00:00:00+08:00,2025-08-23 00:00:00+08:00,True,8,13,2,21,8,23,5,0,219.00
345,345,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-28 06:00:00+08:00,2025-08-28 06:00:00+08:00,True,8,13,2,21,8,28,3,6,345.00
374,374,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-16 23:00:00+08:00,2025-10-16 23:00:00+08:00,True,10,16,3,0,10,16,3,23,23.00
411,411,addity,2025-10-17 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 18:00:00+08:00,2025-10-17 18:00:00+08:00,True,10,17,4,0,10,17,4,18,18.00
412,412,addity,2025-10-17 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 18:00:00+08:00,2025-10-17 18:00:00+08:00,True,10,17,4,0,10,17,4,18,18.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32207,32207,tomato,2026-01-20 17:09:00+08:00,2026-02-06 23:59:00+08:00,2026-02-03 19:00:00+08:00,2026-02-03 19:00:00+08:00,True,1,20,1,17,2,3,1,19,337.85
32212,32212,tomato,2026-01-20 17:09:00+08:00,2026-02-06 23:59:00+08:00,2026-02-04 00:00:00+08:00,2026-02-04 00:00:00+08:00,True,1,20,1,17,2,4,2,0,342.85
32236,32236,tomato,2026-01-20 17:09:00+08:00,2026-02-06 23:59:00+08:00,2026-02-05 00:00:00+08:00,2026-02-05 00:00:00+08:00,True,1,20,1,17,2,5,3,0,366.85
32281,32281,tomato,2026-01-20 17:09:00+08:00,2026-02-06 23:59:00+08:00,2026-02-06 21:00:00+08:00,2026-02-06 21:00:00+08:00,True,1,20,1,17,2,6,4,21,411.85
32484,32484,tomato,2026-03-30 10:00:00+08:00,2026-04-13 23:59:00+08:00,2026-04-07 18:00:00+08:00,2026-04-07 18:00:00+08:00,True,3,30,0,10,4,7,1,18,200.00

In [21]:
df.sample()

,id,username,cycle_start,cycle_end,polling_at,booking_hour,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
2112,2112,anaya,2025-10-30 00:00:00+08:00,2025-11-28 23:59:00+08:00,2025-10-31 07:00:00+08:00,NaT,False,10,30,3,0,10,31,4,7,31.0

In [22]:
df = df.assign(floored=df["polling_at"].dt.floor("h"))
test = df.groupby("floored")["username"].nunique().sort_values(ascending=False)
print(test)
print(len(test))
print(test.mean())


print(df.loc[df["floored"]=="2025-11-27 17:00:00+08:00"]["username"])

floored
2025-11-27 17:00:00+08:00    12
2025-11-27 19:00:00+08:00    12
2025-11-27 18:00:00+08:00    12
2025-11-27 21:00:00+08:00    12
2025-11-27 22:00:00+08:00    12
                             ..
2025-08-12 05:00:00+08:00     1
2025-08-12 06:00:00+08:00     1
2025-08-12 09:00:00+08:00     1
2026-04-26 00:00:00+08:00     1
2026-04-26 17:00:00+08:00     1
Name: username, Length: 5975, dtype: int64
5975
5.344602510460251
2772       anaya
7418     brendon
11321     flower
13326    gohguan
14772        joy
15346        jun
16560         jy
19469        kim
24548        mya
26047      natar
28415       ryan
31589     tomato
Name: username, dtype: str

In [23]:
df.groupby(['polling_dow','polling_hour'])['has_booking'].sum().value_counts()

has_booking
0     55
1     32
2     15
3     12
4     10
6      8
7      7
5      7
9      5
13     4
10     3
12     2
11     2
8      1
19     1
16     1
17     1
14     1
21     1
Name: count, dtype: int64

In [24]:
print(len(df.loc[df["has_booking"]==1]))

538

In [25]:
df.groupby(['username','polling_month','polling_day','polling_hour']) \
  ['has_booking'].sum().value_counts()

has_booking
0     31547
1       304
2        63
4         7
3         6
5         4
12        1
21        1
9         1
Name: count, dtype: int64

In [26]:
test2 = df.groupby(["polling_month","polling_day","polling_hour"])["username"].count()
print(test2)
print(test2.mean())

polling_month  polling_day  polling_hour
1              1            0               12
                            1               10
                            2               10
                            3               10
                            4               10
                                            ..
12             31           19              10
                            20              10
                            21              10
                            22              10
                            23              10
Name: username, Length: 5975, dtype: int64
5.461757322175732