In [1]:
import pandas as pd
from cdc_ml.datasets.poll.poll import generate_df
from cdc_ml.config import BOOKING_CYCLES_PROCESSED,RECORDS_PROCESSED

2026-05-12 13:58:43.594 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df_cycle = pd.read_parquet(BOOKING_CYCLES_PROCESSED)
df_records = pd.read_parquet(RECORDS_PROCESSED)

In [3]:
df = generate_df(df_cycle,df_records)

Empty DataFrame
Columns: [id, username, lesson_at, booking_at, booking_type, class_type, is_one_team]
Index: []
     username               cycle_start                 cycle_end   id  \
1277    apple 2025-11-03 12:01:00+08:00 2025-11-04 23:59:00+08:00  340
1314    apple 2025-11-07 00:00:00+08:00 2025-11-18 23:59:00+08:00  340
1351    apple 2026-01-01 20:35:00+08:00 2026-01-17 23:59:00+08:00  340
1388    apple 2026-01-20 00:00:00+08:00 2026-01-22 23:59:00+08:00  340

     lesson_at                booking_at  booking_type class_type  is_one_team
1277       NaT 2026-01-20 20:00:00+08:00             2          3            0
1314       NaT 2026-01-20 20:00:00+08:00             2          3            0
1351       NaT 2026-01-20 20:00:00+08:00             2          3            0
1388       NaT 2026-01-20 20:00:00+08:00             2          3            0
2026-05-12 13:58:44.041 | INFO     | cdc_ml.datasets.poll.poll:validate_booking_records:63 - All booking records are validated against booking cycle...
          id username               cycle_start                 cycle_end  \
0          0  ajithak 2025-08-19 09:15:00+08:00 2025-08-21 11:00:00+08:00
1          1  ajithak 2025-08-19 09:15:00+08:00 2025-08-21 11:00:00+08:00
2          2  ajithak 2025-08-19 09:15:00+08:00 2025-08-21 11:00:00+08:00
3          3  ajithak 2025-08-19 09:15:00+08:00 2025-08-21 11:00:00+08:00
4          4  ajithak 2025-08-19 09:15:00+08:00 2025-08-21 11:00:00+08:00
...      ...      ...                       ...                       ...
32487  32487   addity 2025-10-16 00:00:00+08:00 2025-10-17 20:00:00+08:00
32488  32488   addity 2025-10-16 00:00:00+08:00 2025-10-17 20:00:00+08:00
32489  32489   addity 2025-10-16 00:00:00+08:00 2025-10-17 20:00:00+08:00
32490  32490   addity 2025-10-16 00:00:00+08:00 2025-10-17 20:00:00+08:00
32491  32491   addity 2025-10-16 00:00:00+08:00 2025-10-17 20:00:00+08:00

                     polling_at  has_booking  cycle_start_dow  \
0     2025-08-19 09:15:00+08:00            0                1
1     2025-08-19 10:15:00+08:00            0                1
2     2025-08-19 11:15:00+08:00            0                1
3     2025-08-19 12:15:00+08:00            0                1
4     2025-08-19 13:15:00+08:00            0                1
...                         ...          ...              ...
32487 2025-10-17 16:00:00+08:00            0                3
32488 2025-10-17 17:00:00+08:00            0                3
32489 2025-10-17 18:00:00+08:00            1                3
32490 2025-10-17 19:00:00+08:00            0                3
32491 2025-10-17 20:00:00+08:00            0                3

       cycle_start_hour  polling_dow  polling_hour
0                     9            1             9
1                     9            1            10
2                     9            1            11
3                     9            1            12
4                     9            1            13
...                 ...          ...           ...
32487                 0            4            16
32488                 0            4            17
32489                 0            4            18
32490                 0            4            19
32491                 0            4            20

[32492 rows x 10 columns]

In [4]:
df.head()

,id,username,cycle_start,cycle_start_dow,cycle_start_hour,cycle_end,polling_at,polling_dow,polling_hour,has_booking
0,0,ajithak,2025-08-19 09:15:00+08:00,1,9,2025-08-21 11:00:00+08:00,2025-08-19 09:15:00+08:00,1,9,0
1,1,ajithak,2025-08-19 09:15:00+08:00,1,9,2025-08-21 11:00:00+08:00,2025-08-19 10:15:00+08:00,1,10,0
2,2,ajithak,2025-08-19 09:15:00+08:00,1,9,2025-08-21 11:00:00+08:00,2025-08-19 11:15:00+08:00,1,11,0
3,3,ajithak,2025-08-19 09:15:00+08:00,1,9,2025-08-21 11:00:00+08:00,2025-08-19 12:15:00+08:00,1,12,0
4,4,ajithak,2025-08-19 09:15:00+08:00,1,9,2025-08-21 11:00:00+08:00,2025-08-19 13:15:00+08:00,1,13,0

In [5]:
df["username"].unique()

<ArrowStringArray>
['ajithak',  'addity',   'bryan', 'lucinda',    'matt', 'ranjith',    'srpr',
      'jy',    'sara',      'bw',     'fir', 'brendon',   'carol',   'isyaf',
     'max',     'jun',     'kim',   'natar',     'mya',   'apple',     'joy',
    'ryan',     'nur',  'flower',  'tomato',   'anmol',  'poopie',    'phuc',
 'gohguan', 'pakning',      'np',   'faith',  'aswath',   'anaya',     'ali',
   'bhara',       'd']
Length: 37, dtype: str

In [6]:
df.loc[df["has_booking"]==1]

,id,username,cycle_start,cycle_start_dow,cycle_start_hour,cycle_end,polling_at,polling_dow,polling_hour,has_booking
48,48,ajithak,2025-08-19 09:15:00+08:00,1,9,2025-08-21 11:00:00+08:00,2025-08-21 09:15:00+08:00,3,9,1
269,269,addity,2025-08-13 21:00:00+08:00,2,21,2025-08-28 11:36:00+08:00,2025-08-23 00:00:00+08:00,5,0,1
395,395,addity,2025-08-13 21:00:00+08:00,2,21,2025-08-28 11:36:00+08:00,2025-08-28 06:00:00+08:00,3,6,1
419,419,addity,2025-10-17 00:00:00+08:00,4,0,2025-10-17 20:00:00+08:00,2025-10-17 18:00:00+08:00,4,18,1
559,559,bryan,2025-08-22 00:48:00+08:00,4,0,2025-09-05 16:00:00+08:00,2025-08-25 12:48:00+08:00,0,12,1
...,...,...,...,...,...,...,...,...,...,...
32150,32150,bhara,2025-10-25 00:00:00+08:00,5,0,2025-10-30 23:59:00+08:00,2025-10-29 15:00:00+08:00,2,15,1
32151,32151,bhara,2025-10-25 00:00:00+08:00,5,0,2025-10-30 23:59:00+08:00,2025-10-29 16:00:00+08:00,2,16,1
32272,32272,d,2025-10-25 00:00:00+08:00,5,0,2025-11-04 23:59:00+08:00,2025-10-28 17:00:00+08:00,1,17,1
32470,32470,addity,2025-10-16 00:00:00+08:00,3,0,2025-10-17 20:00:00+08:00,2025-10-16 23:00:00+08:00,3,23,1
32489,32489,addity,2025-10-16 00:00:00+08:00,3,0,2025-10-17 20:00:00+08:00,2025-10-17 18:00:00+08:00,4,18,1

In [7]:
df.sample()

,id,username,cycle_start,cycle_start_dow,cycle_start_hour,cycle_end,polling_at,polling_dow,polling_hour,has_booking
14266,14266,natar,2025-11-09 00:00:00+08:00,6,0,2025-11-29 23:59:00+08:00,2025-11-27 11:00:00+08:00,3,11,0