In [6]:
import pandas as pd
from cdc_ml.datasets.poll.poll import generate_df
from cdc_ml.config import BOOKING_CYCLES_INTERIM,RECORDS_PROCESSED,CUSTOMER_CLASS_INTERIM

In [7]:
df_cycle = pd.read_parquet(BOOKING_CYCLES_INTERIM)
df_records = pd.read_parquet(RECORDS_PROCESSED)
df_class = pd.read_parquet(CUSTOMER_CLASS_INTERIM)

In [8]:
df = generate_df(df_cycle,df_records,df_class)

2026-05-07 15:13:59.540 | INFO     | cdc_ml.datasets.poll.poll:validate_booking_records:62 - All booking records are validated against booking cycle...

In [9]:
df

,id,username,cycle_start,cycle_end,polling_hour,has_booking,class_type,is_one_team
0,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 09:15:00+08:00,0,3,0
1,1,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 10:15:00+08:00,0,3,0
2,2,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 11:15:00+08:00,0,3,0
3,3,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 12:15:00+08:00,0,3,0
4,4,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 13:15:00+08:00,0,3,0
...,...,...,...,...,...,...,...,...
34817,32631,d,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00,2025-11-04 19:00:00+08:00,0,3,0
34818,32632,d,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00,2025-11-04 20:00:00+08:00,0,3,0
34819,32633,d,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00,2025-11-04 21:00:00+08:00,0,3,0
34820,32634,d,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00,2025-11-04 22:00:00+08:00,0,3,0
34821,32635,d,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00,2025-11-04 23:00:00+08:00,0,3,0

In [10]:
df.loc[df["has_booking"]==1]

,id,username,cycle_start,cycle_end,polling_hour,has_booking,class_type,is_one_team
48,48,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-21 09:15:00+08:00,1,3,0
269,269,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-23 00:00:00+08:00,1,3a,1
395,395,addity,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00,2025-08-28 06:00:00+08:00,1,3a,1
424,424,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-16 23:00:00+08:00,1,3a,1
443,443,addity,2025-10-16 00:00:00+08:00,2025-10-17 20:00:00+08:00,2025-10-17 18:00:00+08:00,1,3a,1
...,...,...,...,...,...,...,...,...
34492,32339,bhara,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00,2025-10-29 15:00:00+08:00,1,3,0
34493,32339,bhara,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00,2025-10-29 15:00:00+08:00,1,3,0
34494,32340,bhara,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00,2025-10-29 16:00:00+08:00,1,3,0
34495,32340,bhara,2025-10-25 00:00:00+08:00,2025-10-30 23:59:00+08:00,2025-10-29 16:00:00+08:00,1,3,0
34647,32461,d,2025-10-25 00:00:00+08:00,2025-11-04 23:59:00+08:00,2025-10-28 17:00:00+08:00,1,3,0

In [11]:
df.sample()

,id,username,cycle_start,cycle_end,polling_hour,has_booking,class_type,is_one_team
7923,7923,brendon,2025-11-04 00:00:00+08:00,2025-11-06 23:59:00+08:00,2025-11-04 08:00:00+08:00,0,3a,0