In [1]:
import pandas as pd
from cdc_ml.config import PREFERENCE_EXTERNAL,RECORDS_PROCESSED
from cdc_ml.datasets.constants import TIMESLOTS
from cdc_ml.datasets.preference.preference import clean_df

2026-06-06 15:23:17.415 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df_pref = pd.read_excel(PREFERENCE_EXTERNAL)

In [3]:
df_records = pd.read_parquet(RECORDS_PROCESSED)

In [4]:
df_pref.head()

,id,username,pref_start,pref_end,mon,tues,wed,thurs,fri,sat,sun,interval
0,0,ajithak,2025-08-19,2025-08-31,"5,6","5,6","5,6","5,6","5,6","5,6","0,1,2,3,4,5,6",D
1,1,addity,2025-08-13,2025-09-30,"5,6",NaN,"5,6",NaN,"5,6",NaN,"0,1,2,3,4,5,6",D
2,2,addity,2025-10-27,2025-12-14,"5,6","5,6","5,6","5,6","5,6","0,1,2,3,4,5,6","0,1,2,3,4,5,6",D
3,3,addity,2026-01-16,2026-02-28,"5,6","5,6","5,6","5,6","0,1,2,3,4,5,6","0,1,2,3,4,5,6","0,1,2,3,4,5,6",D
4,4,bryan,2025-08-22,2025-09-24,6,6,6,6,6,"2,3,4,5,6","2,3,4,5,6",D

In [5]:
df_records.head()

,id,username,lesson_at,booking_at,booking_type,class_type,is_one_team
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0,3,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0,3,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0,3a,1
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0,3a,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0,3a,0

In [6]:
df = clean_df(df_pref,df_records)

2026-06-06 15:23:18.002 | INFO     | cdc_ml.datasets.preference.preference:all_records_valid:109 - All records verified

In [7]:
df.head()

,id,username,day_of_week,pref_start,pref_end,date,t_0830,t_1020,t_1245,t_1435,t_1625,t_1850,t_2040
0,0,ajithak,1,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-19 23:00:00+08:00,0,0,0,0,0,1,1
1,0,ajithak,2,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-20 23:00:00+08:00,0,0,0,0,0,1,1
2,0,ajithak,3,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-21 23:00:00+08:00,0,0,0,0,0,1,1
3,0,ajithak,4,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-22 23:00:00+08:00,0,0,0,0,0,1,1
4,0,ajithak,5,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-23 23:00:00+08:00,0,0,0,0,0,1,1

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2534 entries, 0 to 2533
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           2534 non-null   int64
 1   username     2534 non-null   str
 2   day_of_week  2534 non-null   int64
 3   pref_start   2534 non-null   datetime64[us, Asia/Singapore]
 4   pref_end     2534 non-null   datetime64[ns, Asia/Singapore]
 5   date         2534 non-null   datetime64[us, Asia/Singapore]
 6   t_0830       2534 non-null   int64
 7   t_1020       2534 non-null   int64
 8   t_1245       2534 non-null   int64
 9   t_1435       2534 non-null   int64
 10  t_1625       2534 non-null   int64
 11  t_1850       2534 non-null   int64
 12  t_2040       2534 non-null   int64
dtypes: datetime64[ns, Asia/Singapore](1), datetime64[us, Asia/Singapore](2), int64(9), str(1)
memory usage: 267.9 KB