In [2]:
import pandas as pd
from cdc_ml.config import PREFERENCE_EXTERNAL,RECORDS_PROCESSED
from cdc_ml.datasets.constants import TIMESLOTS
from cdc_ml.datasets.preference.preference import clean_df

2026-06-03 11:50:25.282 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [3]:
df_pref = pd.read_excel(PREFERENCE_EXTERNAL)

In [4]:
df_records = pd.read_parquet(RECORDS_PROCESSED)

In [5]:
df_pref.head()

,id,username,pref_start,pref_end,mon,tues,wed,thurs,fri,sat,sun,interval
0,0,ajithak,2025-08-19,2025-08-31,"5,6","5,6","5,6","5,6","5,6","5,6","0,1,2,3,4,5,6",D
1,1,addity,2025-08-13,2025-09-30,"5,6",NaN,"5,6",NaN,"5,6",NaN,"0,1,2,3,4,5,6",D
2,2,addity,2025-10-27,2025-12-14,"5,6","5,6","5,6","5,6","5,6","0,1,2,3,4,5,6","0,1,2,3,4,5,6",D
3,3,addity,2026-01-16,2026-02-28,"5,6","5,6","5,6","5,6","0,1,2,3,4,5,6","0,1,2,3,4,5,6","0,1,2,3,4,5,6",D
4,4,bryan,2025-08-22,2025-09-24,6,6,6,6,6,"2,3,4,5,6","2,3,4,5,6",D

In [6]:
df_records.head()

,id,username,lesson_at,booking_at,booking_type,class_type,is_one_team
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0,3,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0,3,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0,3a,1
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0,3a,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0,3a,0

In [7]:
df = clean_df(df_pref,df_records)

                       mon                   tues                    wed  \
0                   (5, 6)                 (5, 6)                 (5, 6)
1                   (5, 6)                     ()                 (5, 6)
2                   (5, 6)                 (5, 6)                 (5, 6)
3                   (5, 6)                 (5, 6)                 (5, 6)
4                     (6,)                   (6,)                   (6,)
..                     ...                    ...                    ...
255  (0, 1, 2, 3, 4, 5, 6)  (0, 1, 2, 3, 4, 5, 6)  (0, 1, 2, 3, 4, 5, 6)
256  (0, 1, 2, 3, 4, 5, 6)  (0, 1, 2, 3, 4, 5, 6)  (0, 1, 2, 3, 4, 5, 6)
257              (4, 5, 6)              (4, 5, 6)              (4, 5, 6)
258                 (5, 6)                 (5, 6)                 (5, 6)
259                 (5, 6)                 (5, 6)                 (5, 6)

                     thurs                    fri                    sat  \
0                   (5, 6)                 (5, 6)                 (5, 6)
1                       ()                 (5, 6)                     ()
2                   (5, 6)                 (5, 6)  (0, 1, 2, 3, 4, 5, 6)
3                   (5, 6)  (0, 1, 2, 3, 4, 5, 6)  (0, 1, 2, 3, 4, 5, 6)
4                     (6,)                   (6,)        (2, 3, 4, 5, 6)
..                     ...                    ...                    ...
255  (0, 1, 2, 3, 4, 5, 6)  (0, 1, 2, 3, 4, 5, 6)  (0, 1, 2, 3, 4, 5, 6)
256  (0, 1, 2, 3, 4, 5, 6)  (0, 1, 2, 3, 4, 5, 6)  (0, 1, 2, 3, 4, 5, 6)
257              (4, 5, 6)              (4, 5, 6)              (4, 5, 6)
258                 (5, 6)                 (5, 6)                 (5, 6)
259                 (5, 6)                 (5, 6)  (0, 1, 2, 3, 4, 5, 6)

                       sun
0    (0, 1, 2, 3, 4, 5, 6)
1    (0, 1, 2, 3, 4, 5, 6)
2    (0, 1, 2, 3, 4, 5, 6)
3    (0, 1, 2, 3, 4, 5, 6)
4          (2, 3, 4, 5, 6)
..                     ...
255  (0, 1, 2, 3, 4, 5, 6)
256  (0, 1, 2, 3, 4, 5, 6)
257              (4, 5, 6)
258                 (5, 6)
259  (0, 1, 2, 3, 4, 5, 6)

[260 rows x 7 columns]
2026-06-03 11:50:26.285 | INFO     | cdc_ml.datasets.preference.preference:all_records_valid:108 - All records verified

C:\Users\zhiju\Desktop\cdc_ml\cdc_ml\datasets\preference\preference.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_long["pref_at"] = pd.to_datetime(

In [8]:
df.head()

,id,username,day_of_week,pref_start,pref_end,date,t_0830,t_1020,t_1245,t_1435,t_1625,t_1850,t_2040,mon,tues,wed,thurs,fri,sat,sun
0,0,ajithak,1,2025-08-19 00:00:00+08:00,2025-08-31 00:00:00+08:00,2025-08-19 00:00:00+08:00,0,0,0,0,0,1,1,"(5, 6)","(5, 6)","(5, 6)","(5, 6)","(5, 6)","(5, 6)","(0, 1, 2, 3, 4, 5, 6)"
1,0,ajithak,2,2025-08-19 00:00:00+08:00,2025-08-31 00:00:00+08:00,2025-08-20 00:00:00+08:00,0,0,0,0,0,1,1,"(5, 6)",(),"(5, 6)",(),"(5, 6)",(),"(0, 1, 2, 3, 4, 5, 6)"
2,0,ajithak,3,2025-08-19 00:00:00+08:00,2025-08-31 00:00:00+08:00,2025-08-21 00:00:00+08:00,0,0,0,0,0,1,1,"(5, 6)","(5, 6)","(5, 6)","(5, 6)","(5, 6)","(0, 1, 2, 3, 4, 5, 6)","(0, 1, 2, 3, 4, 5, 6)"
3,0,ajithak,4,2025-08-19 00:00:00+08:00,2025-08-31 00:00:00+08:00,2025-08-22 00:00:00+08:00,0,0,0,0,0,1,1,"(5, 6)","(5, 6)","(5, 6)","(5, 6)","(0, 1, 2, 3, 4, 5, 6)","(0, 1, 2, 3, 4, 5, 6)","(0, 1, 2, 3, 4, 5, 6)"
4,0,ajithak,5,2025-08-19 00:00:00+08:00,2025-08-31 00:00:00+08:00,2025-08-23 00:00:00+08:00,0,0,0,0,0,1,1,"(6,)","(6,)","(6,)","(6,)","(6,)","(2, 3, 4, 5, 6)","(2, 3, 4, 5, 6)"

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2517 entries, 0 to 2516
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id           2517 non-null   int64
 1   username     2517 non-null   str
 2   day_of_week  2517 non-null   int64
 3   pref_start   2517 non-null   datetime64[us, Asia/Singapore]
 4   pref_end     2517 non-null   datetime64[ns, Asia/Singapore]
 5   date         2517 non-null   datetime64[us, Asia/Singapore]
 6   t_0830       2517 non-null   int64
 7   t_1020       2517 non-null   int64
 8   t_1245       2517 non-null   int64
 9   t_1435       2517 non-null   int64
 10  t_1625       2517 non-null   int64
 11  t_1850       2517 non-null   int64
 12  t_2040       2517 non-null   int64
 13  mon          260 non-null    object
 14  tues         260 non-null    object
 15  wed          260 non-null    object
 16  thurs        260 non-null    object
 17  fri          260 non-null    object
 18  sat          260 non-null    object
 19  sun          260 non-null    object
dtypes: datetime64[ns, Asia/Singapore](1), datetime64[us, Asia/Singapore](2), int64(9), object(7), str(1)
memory usage: 403.7+ KB

In [10]:

TIME_COLS = {
"t_0830": "08:30",
"t_1020": "10:20",
"t_1245": "12:45",
"t_1435": "14:35",
"t_1625": "16:25",
"t_1850": "18:50",
"t_2040": "20:40",
}
print(list(TIME_COLS))

['t_0830', 't_1020', 't_1245', 't_1435', 't_1625', 't_1850', 't_2040']

In [11]:
df.loc[df["username"]=="jy"]

,id,username,day_of_week,pref_start,pref_end,date,t_0830,t_1020,t_1245,t_1435,t_1625,t_1850,t_2040,mon,tues,wed,thurs,fri,sat,sun
458,14,jy,6,2025-09-14 00:00:00+08:00,2025-10-07 00:00:00+08:00,2025-09-14 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
459,14,jy,0,2025-09-14 00:00:00+08:00,2025-10-07 00:00:00+08:00,2025-09-15 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
460,14,jy,1,2025-09-14 00:00:00+08:00,2025-10-07 00:00:00+08:00,2025-09-16 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
461,14,jy,2,2025-09-14 00:00:00+08:00,2025-10-07 00:00:00+08:00,2025-09-17 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
462,14,jy,3,2025-09-14 00:00:00+08:00,2025-10-07 00:00:00+08:00,2025-09-18 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
612,20,jy,0,2026-02-16 00:00:00+08:00,2026-02-16 00:00:00+08:00,2026-02-16 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
613,20,jy,4,2026-02-20 00:00:00+08:00,2026-02-21 00:00:00+08:00,2026-02-20 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
614,20,jy,5,2026-02-20 00:00:00+08:00,2026-02-21 00:00:00+08:00,2026-02-21 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
615,20,jy,0,2026-02-23 00:00:00+08:00,2026-02-24 00:00:00+08:00,2026-02-23 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
616,20,jy,1,2026-02-23 00:00:00+08:00,2026-02-24 00:00:00+08:00,2026-02-24 00:00:00+08:00,1,1,1,1,1,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN