In [1]:
import pandas as pd 
from cdc_ml.features.build_features import *
from cdc_ml.config import POLLS_PROCESSED,CUSTOMER_CLASS_PROCESSED,PREFERENCE_PROCESSED

2026-05-14 16:15:10.760 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df_poll = pd.read_parquet(POLLS_PROCESSED)
df_class = pd.read_parquet(CUSTOMER_CLASS_PROCESSED)
df_pref = pd.read_parquet(PREFERENCE_PROCESSED)

In [3]:
df_poll.head()

,id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
0,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 09:15:00+08:00,0,8,19,1,9,8,19,1,9,0.0
1,1,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 10:15:00+08:00,0,8,19,1,9,8,19,1,10,1.0
2,2,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 11:15:00+08:00,0,8,19,1,9,8,19,1,11,2.0
3,3,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 12:15:00+08:00,0,8,19,1,9,8,19,1,12,3.0
4,4,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 13:15:00+08:00,0,8,19,1,9,8,19,1,13,4.0

In [4]:
df_class.head()

     username              class_type  is_one_team
0  admin user                      3a            0
1          jj                      3a            0
2           b                      3a            0
3           g                      3a            0
4    shahtiya  CLASS 3 PRACTICAL TEST            0

In [5]:
df_pref.head()

,id,username,day_of_week,day_name,pref_start,pref_end,date,t_0830,t_1020,t_1245,t_1435,t_1625,t_1850,t_2040
0,0,ajithak,1,Tuesday,2025-08-19,2025-08-31,2025-08-19,0,0,0,0,0,1,1
1,0,ajithak,2,Wednesday,2025-08-19,2025-08-31,2025-08-20,0,0,0,0,0,1,1
2,0,ajithak,3,Thursday,2025-08-19,2025-08-31,2025-08-21,0,0,0,0,0,1,1
3,0,ajithak,4,Friday,2025-08-19,2025-08-31,2025-08-22,0,0,0,0,0,1,1
4,0,ajithak,5,Saturday,2025-08-19,2025-08-31,2025-08-23,0,0,0,0,0,1,1

In [6]:
df_poll = assign_class_type(df_poll,df_class)

In [7]:
df_poll = drop_meta_high_card_cols(df_poll)

In [8]:
df_poll.head()

,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle,class_type,is_one_team
0,0,8,19,1,9,8,19,1,9,0.0,0,0
1,0,8,19,1,9,8,19,1,10,1.0,0,0
2,0,8,19,1,9,8,19,1,11,2.0,0,0
3,0,8,19,1,9,8,19,1,12,3.0,0,0
4,0,8,19,1,9,8,19,1,13,4.0,0,0