In [1]:
import pandas as pd 
from cdc_ml.features.build_features import *
from cdc_ml.config import POLLS_PROCESSED,CUSTOMER_CLASS_PROCESSED,PREFERENCE_PROCESSED
from cdc_ml.features.build_features import build_features

2026-06-06 15:28:31.359 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:
df_poll = pd.read_parquet(POLLS_PROCESSED)
df_class = pd.read_parquet(CUSTOMER_CLASS_PROCESSED)
df_pref = pd.read_parquet(PREFERENCE_PROCESSED)

In [3]:
df_poll.head()

,id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,polling_month,polling_day,polling_dow,polling_hour,hours_into_cycle
0,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 09:00:00+08:00,False,8,19,1,9,8,19,1,9,-0.25
1,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 10:00:00+08:00,False,8,19,1,9,8,19,1,10,0.75
2,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 11:00:00+08:00,False,8,19,1,9,8,19,1,11,1.75
3,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 12:00:00+08:00,False,8,19,1,9,8,19,1,12,2.75
4,0,ajithak,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00,2025-08-19 13:00:00+08:00,False,8,19,1,9,8,19,1,13,3.75

In [4]:
df_class.head()

     username              class_type  is_one_team
0  admin user                      3a            0
1          jj                      3a            0
2           b                      3a            0
3           g                      3a            0
4    shahtiya  CLASS 3 PRACTICAL TEST            0

In [5]:
df_pref.head()

,id,username,day_of_week,pref_start,pref_end,date,t_0830,t_1020,t_1245,t_1435,t_1625,t_1850,t_2040,mon,tues,wed,thurs,fri,sat,sun
0,0,ajithak,1,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-19 23:00:00+08:00,0,0,0,0,0,1,1,"[5, 6]","[5, 6]","[5, 6]","[5, 6]","[5, 6]","[5, 6]","[0, 1, 2, 3, 4, 5, 6]"
1,0,ajithak,2,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-20 23:00:00+08:00,0,0,0,0,0,1,1,"[5, 6]",[],"[5, 6]",[],"[5, 6]",[],"[0, 1, 2, 3, 4, 5, 6]"
2,0,ajithak,3,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-21 23:00:00+08:00,0,0,0,0,0,1,1,"[5, 6]","[5, 6]","[5, 6]","[5, 6]","[5, 6]","[0, 1, 2, 3, 4, 5, 6]","[0, 1, 2, 3, 4, 5, 6]"
3,0,ajithak,4,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-22 23:00:00+08:00,0,0,0,0,0,1,1,"[5, 6]","[5, 6]","[5, 6]","[5, 6]","[0, 1, 2, 3, 4, 5, 6]","[0, 1, 2, 3, 4, 5, 6]","[0, 1, 2, 3, 4, 5, 6]"
4,0,ajithak,5,2025-08-19 00:00:00+08:00,2025-08-31 23:00:00+08:00,2025-08-23 23:00:00+08:00,0,0,0,0,0,1,1,[6],[6],[6],[6],[6],"[2, 3, 4, 5, 6]","[2, 3, 4, 5, 6]"

In [6]:
df = build_features(df_poll,df_pref,df_class)

In [7]:
df.head()

,id,username,cycle_start,cycle_end,polling_at,has_booking,cycle_start_month,cycle_start_day,cycle_start_dow,cycle_start_hour,...,pref_unique_timeslot,pref_dow_count_0,pref_dow_count_1,pref_dow_count_2,pref_dow_count_3,pref_dow_count_4,pref_dow_count_5,pref_dow_count_6,date,pref_valid
1126,6,matt,2025-08-12 01:21:00+08:00,2025-09-23 23:52:00+08:00,2025-08-12 06:00:00+08:00,False,8,12,1,1,...,5,2,2,2,2,1,3,3,"[2025-08-18 23:00:00+08:00, 2025-08-19 23:00:0...",57
1218,6,matt,2025-08-12 01:21:00+08:00,2025-09-23 23:52:00+08:00,2025-08-16 02:00:00+08:00,False,8,12,1,1,...,5,2,2,2,2,1,3,3,"[2025-08-18 23:00:00+08:00, 2025-08-19 23:00:0...",57
1217,6,matt,2025-08-12 01:21:00+08:00,2025-09-23 23:52:00+08:00,2025-08-16 01:00:00+08:00,False,8,12,1,1,...,5,2,2,2,2,1,3,3,"[2025-08-18 23:00:00+08:00, 2025-08-19 23:00:0...",57
1216,6,matt,2025-08-12 01:21:00+08:00,2025-09-23 23:52:00+08:00,2025-08-16 00:00:00+08:00,False,8,12,1,1,...,5,2,2,2,2,1,3,3,"[2025-08-18 23:00:00+08:00, 2025-08-19 23:00:0...",57
1215,6,matt,2025-08-12 01:21:00+08:00,2025-09-23 23:52:00+08:00,2025-08-15 23:00:00+08:00,False,8,12,1,1,...,5,2,2,2,2,1,3,3,"[2025-08-18 23:00:00+08:00, 2025-08-19 23:00:0...",57