In [1]:
import pandas as pd
from cdc_ml.config import PREFERENCE_EXTERNAL,RECORDS_PROCESSED,BOOKING_CYCLES_INTERIM,RECORDS_PROCESSED
from cdc_ml.datasets.preference.preference import clean_df

2026-05-08 23:03:06.119 | INFO     | cdc_ml.config:<module>:12 - PROJ_ROOT path is: C:\Users\zhiju\Desktop\cdc_ml

In [2]:

df_pref = pd.read_excel(PREFERENCE_EXTERNAL)
df_records= pd.read_parquet(RECORDS_PROCESSED)
df_cycle = pd.read_parquet(BOOKING_CYCLES_INTERIM)

In [3]:
df_cycle.head()

,id,username,preference,range,cycle_end_reason,cycle_start,cycle_end
0,0,ajithak,"monday to saturday after 5pm , sunday anytime",till next week,completed,2025-08-19 09:15:00+08:00,2025-08-21 11:00:00+08:00
1,1,addity,"weeday after 7 , no tues and thurs",before oct,completed,2025-08-13 21:00:00+08:00,2025-08-28 11:36:00+08:00
2,2,addity,"anytime on weekends , weekday after 630pm",26 oct to 14 dec,completed,2025-10-17 00:00:00+08:00,2025-10-17 20:00:00+08:00
3,3,addity,"friday and weekends anytime, other weekdays af...",Jan and feb,completed,2026-01-16 20:00:00+08:00,2026-01-19 00:00:00+08:00
4,4,bryan,"before 25 sept , weekday after 730pm , 12 pm o...",NaN,completed,2025-08-22 00:48:00+08:00,2025-09-05 16:00:00+08:00

In [4]:
df_records.head()

,id,username,lesson_at,booking_at,booking_type,class_type,is_one_team
0,0,ajithak,2025-08-28 18:50:00+08:00,2025-08-21 09:24:06.300383+08:00,0,3,0
1,1,ajithak,2025-08-28 20:40:00+08:00,2025-08-21 09:24:16.048708+08:00,0,3,0
2,2,addity,2025-09-21 14:35:00+08:00,2025-08-23 00:57:26.576198+08:00,0,3a,1
3,3,bryan,2025-08-28 20:40:00+08:00,2025-08-25 12:06:06.539664+08:00,0,3a,0
4,4,bryan,2025-08-31 12:45:00+08:00,2025-08-26 12:50:24.317931+08:00,0,3a,0

In [5]:
df_pref.head()

,Unnamed: 0,id,username,pref_start,pref_end,mon,tues,wed,thurs,fri,sat,sun,interval
0,0,0,ajithak,2025-08-19,2025-08-31,"5,6","5,6","5,6","5,6","5,6","5,6","0,1,2,3,4,5,6",D
1,1,1,addity,2025-08-13,2025-09-30,"5,6",NaN,"5,6",NaN,"5,6",NaN,"0,1,2,3,4,5,6",D
2,2,2,addity,2025-10-27,2025-12-14,"5,6","5,6","5,6","5,6","5,6","0,1,2,3,4,5,6","0,1,2,3,4,5,6",D
3,3,3,addity,2026-01-16,2026-02-28,"5,6","5,6","5,6","5,6","0,1,2,3,4,5,6","0,1,2,3,4,5,6","0,1,2,3,4,5,6",D
4,4,4,bryan,2025-08-22,2025-09-24,6,6,6,6,6,"2,3,4,5,6","2,3,4,5,6",D

In [6]:
df = clean_df(df_pref,df_records)

   id username  day_of_week   day_name pref_start   pref_end       date  \
0   0  ajithak            1    Tuesday 2025-08-19 2025-08-31 2025-08-19
1   0  ajithak            2  Wednesday 2025-08-19 2025-08-31 2025-08-20
2   0  ajithak            3   Thursday 2025-08-19 2025-08-31 2025-08-21
3   0  ajithak            4     Friday 2025-08-19 2025-08-31 2025-08-22
4   0  ajithak            5   Saturday 2025-08-19 2025-08-31 2025-08-23

   t_0830  t_1020  t_1245  t_1435  t_1625  t_1850  t_2040
0       0       0       0       0       0       1       1
1       0       0       0       0       0       1       1
2       0       0       0       0       0       1       1
3       0       0       0       0       0       1       1
4       0       0       0       0       0       1       1
        id username                   pref_at
0        0  ajithak 2025-08-19 18:50:00+08:00
1        0  ajithak 2025-08-19 20:40:00+08:00
2        0  ajithak 2025-08-20 18:50:00+08:00
3        0  ajithak 2025-08-20 20:40:00+08:00
4        0  ajithak 2025-08-21 18:50:00+08:00
...    ...      ...                       ...
20838  121   addity 2025-12-14 12:45:00+08:00
20839  121   addity 2025-12-14 14:35:00+08:00
20840  121   addity 2025-12-14 16:25:00+08:00
20841  121   addity 2025-12-14 18:50:00+08:00
20842  121   addity 2025-12-14 20:40:00+08:00

[20843 rows x 3 columns]
Empty DataFrame
Columns: [username, lesson_at, booking_at]
Index: []

In [7]:
df.head()

,id,username,day_of_week,day_name,pref_start,pref_end,date,t_0830,t_1020,t_1245,t_1435,t_1625,t_1850,t_2040
0,0,ajithak,1,Tuesday,2025-08-19,2025-08-31,2025-08-19,0,0,0,0,0,1,1
1,0,ajithak,2,Wednesday,2025-08-19,2025-08-31,2025-08-20,0,0,0,0,0,1,1
2,0,ajithak,3,Thursday,2025-08-19,2025-08-31,2025-08-21,0,0,0,0,0,1,1
3,0,ajithak,4,Friday,2025-08-19,2025-08-31,2025-08-22,0,0,0,0,0,1,1
4,0,ajithak,5,Saturday,2025-08-19,2025-08-31,2025-08-23,0,0,0,0,0,1,1