In [38]:
import pandas as pd

In [39]:
df = pd.read_csv("../data/raw/records.csv",index_col="id")

In [40]:
df.head()

,username,booking,created_at
id,,,
1,test,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-05 16:05:19.533091+00:00
19,0,"Date: 2025-08-14 , Time: 20:40 - 22:20",2025-08-08 15:14:18.789640+00:00
20,00860768,"Date: 2025-08-31 , Time: 10:20 - 12:00",2025-08-10 07:39:16.993798+00:00
21,00860768,"Date: 2025-08-12 , Time: 14:15 - 15:05",2025-08-10 17:09:18.087665+00:00
22,00860768,"Date: 2025-08-19 , Time: 11:15 - 12:05",2025-08-10 17:09:40.512199+00:00

In [46]:
df.loc[df["username"]=="Tomato",["booking",'created_at']]

,booking,created_at
id,,
303,"Date: 2025-12-04 , Time: 10:20 - 12:00",2025-11-26 06:48:00.567260+00:00
305,"Date: 2025-12-04 , Time: 16:25 - 18:05",2025-11-26 16:05:31.426978+00:00
306,"Date: 2025-12-04 , Time: 18:50 - 20:30",2025-11-26 16:07:35.374889+00:00
307,"Date: 2025-12-04 , Time: 20:40 - 22:20",2025-11-26 16:09:46.378972+00:00
308,"Date: 2025-12-01 , Time: 10:20 - 12:00",2025-11-26 16:52:23.703690+00:00
334,"Slots booked:\nDate: 02/01/2026, Time: 18:50 -...",2025-12-25 16:05:19.358753+00:00
346,"Slots booked:\nDate: 08/01/2026, Time: 18:50 -...",2025-12-31 16:01:42.283791+00:00
347,"Slots booked:\nDate: 08/01/2026, Time: 20:40 -...",2025-12-31 16:02:24.070906+00:00
350,"Slots booked:\nDate: 09/01/2026, Time: 20:40 -...",2026-01-01 16:02:54.292044+00:00
359,"Slots booked:\nDate: 15/01/2026, Time: 20:40 -...",2026-01-07 16:18:17.818164+00:00
387,"Slots booked:\nDate: 24/02/2026, Time: 14:35 -...",2026-01-27 05:08:14.315798+00:00
389,"Slots booked:\nDate: 02/02/2026, Time: 16:25 -...",2026-01-28 00:21:27.529921+00:00
390,"Slots booked:\nDate: 05/02/2026, Time: 16:25 -...",2026-01-28 16:02:00.868797+00:00
393,"Slots booked:\nDate: 05/02/2026, Time: 16:25 -...",2026-02-03 11:43:56.634742+00:00
394,"Slots booked:\nDate: 09/02/2026, Time: 16:25 -...",2026-02-03 16:11:25.791179+00:00
396,"Slots booked:\nDate: 12/02/2026, Time: 16:25 -...",2026-02-04 16:27:43.326324+00:00
397,"Slots booked:\nDate: 10/02/2026, Time: 14:35 -...",2026-02-06 13:39:10.386934+00:00
439,"Slots booked:\nDate: 13/04/2026, Time: 08:30 -...",2026-04-07 10:55:41.082360+00:00